##***Data Preprocessing***

In [ ]:
Netflix_Clustering = Netflix_data.copy()

In [ ]:
# Handling Missing Values & Missing Value Imputation
Netflix_Clustering.isnull().sum()

type              0
country         507
date_added       10
release_year      0
rating            7
duration          0
listed_in         0
description       0
year_added       10
month_added      10
main_genre        0
dtype: int64

In [ ]:
Netflix_Clustering['country'].fillna('Unknown', inplace=True)
Netflix_Clustering['rating'].fillna('Not Rated', inplace=True)

/tmp/ipykernel_7684/1206264581.py:1: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.



/tmp/ipykernel_7684/1206264581.py:2: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [ ]:
Netflix_Clustering.dropna(
    subset=['date_added', 'year_added', 'month_added'],
    inplace=True
)

In [ ]:
Netflix_Clustering.drop('date_added', axis = 1, inplace = True)
# We have already extracted information from it in the form of year_added & mobth_added columns so we don't need this feature/column for training our algorithm

In [ ]:
Netflix_Clustering.shape

(7777, 10)

In [ ]:
# Handling Outliers & Outlier treatments
Netflix_Clustering['movie_duration']  = Netflix_Clustering.apply(lambda x: x['duration'] if x['type'] == 'Movie' else 0, axis = 1 )
Netflix_Clustering['tv_show_seasons'] = Netflix_Clustering.apply(lambda x: x['duration'] if x['type'] == 'TV Show' else 0, axis = 1)

In [ ]:
Netflix_Clustering.drop(['duration'], axis = 1, inplace = True)

In [ ]:
#We are performing this step because, when we applied encoding the feature size was around 774 features, even after applying pca the feature size was 702.
#So we need to select only top 10-15 countries so that feature size will not increase
top_countries = Netflix_Clustering['country'].value_counts().head(15).index
Netflix_Clustering['country'] = Netflix_Clustering['country'].apply(
    lambda x: x if x in top_countries else 'Other'
)

In [ ]:
Netflix_Clustering.shape

(7777, 11)

In [ ]:
# Encode your categorical columns
Netflix_Clustering['listed_in'] = Netflix_Clustering['listed_in'].apply(lambda x: x.split(','))

In [ ]:
Netflix_Clustering.head()

,type,country,release_year,rating,listed_in,description,year_added,month_added,main_genre,movie_duration,tv_show_seasons
0,TV Show,Brazil,2020,TV-MA,"[International TV Shows, TV Dramas, TV Sci-F...",In a future where the elite inhabit an island ...,2020.0,8.0,International TV Shows,0,4
1,Movie,Mexico,2016,TV-MA,"[Dramas, International Movies]",After a devastating earthquake hits Mexico Cit...,2016.0,12.0,Dramas,93,0
2,Movie,Other,2011,R,"[Horror Movies, International Movies]","When an army recruit is found dead, his fellow...",2018.0,12.0,Horror Movies,78,0
3,Movie,United States,2009,PG-13,"[Action & Adventure, Independent Movies, Sci...","In a postapocalyptic world, rag-doll robots hi...",2017.0,11.0,Action & Adventure,80,0
4,Movie,United States,2008,PG-13,[Dramas],A brilliant group of students become card-coun...,2020.0,1.0,Dramas,123,0

In [ ]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()

genre_df = pd.DataFrame(
    mlb.fit_transform(Netflix_Clustering['listed_in']),
    columns=mlb.classes_,
    index=Netflix_Clustering.index
)

Netflix_Clustering = pd.concat([Netflix_Clustering, genre_df], axis=1)

In [ ]:
Netflix_Clustering.shape

(7777, 84)

In [ ]:
Netflix_Clustering.head()

,type,country,release_year,rating,listed_in,description,year_added,month_added,main_genre,movie_duration,...,Sports Movies,Stand-Up Comedy,Stand-Up Comedy & Talk Shows,TV Action & Adventure,TV Comedies,TV Dramas,TV Horror,TV Sci-Fi & Fantasy,TV Shows,Thrillers
0,TV Show,Brazil,2020,TV-MA,"[International TV Shows, TV Dramas, TV Sci-F...",In a future where the elite inhabit an island ...,2020.0,8.0,International TV Shows,0,...,0,0,0,0,0,0,0,0,0,0
1,Movie,Mexico,2016,TV-MA,"[Dramas, International Movies]",After a devastating earthquake hits Mexico Cit...,2016.0,12.0,Dramas,93,...,0,0,0,0,0,0,0,0,0,0
2,Movie,Other,2011,R,"[Horror Movies, International Movies]","When an army recruit is found dead, his fellow...",2018.0,12.0,Horror Movies,78,...,0,0,0,0,0,0,0,0,0,0
3,Movie,United States,2009,PG-13,"[Action & Adventure, Independent Movies, Sci...","In a postapocalyptic world, rag-doll robots hi...",2017.0,11.0,Action & Adventure,80,...,0,0,0,0,0,0,0,0,0,0
4,Movie,United States,2008,PG-13,[Dramas],A brilliant group of students become card-coun...,2020.0,1.0,Dramas,123,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
Netflix_Clustering.shape

(7777, 111)

In [ ]:
Netflix_Clustering_exp2 = Netlfix_Clustering.copy()